INSERT INTO filme (nome, ano, descricao) VALUES
('A Origem', 2010, 'Um thriller alucinante sobre sonhos dentro de sonhos.'),
('Matrix', 1999, 'Um hacker descobre que a realidade em que vive é uma simulação.'),
('Interestelar', 2014, 'Uma equipe de exploradores viaja através de um buraco de minhoca no espaço.'),
('O Poderoso Chefão', 1972, 'O patriarca envelhecido de uma dinastia do crime organizado transfere o controle para seu filho relutante.'),
('Pulp Fiction: Tempo de Violência', 1994, 'As vidas de dois assassinos de aluguel, um boxeador e outros se entrelaçam em quatro contos de violência e redenção.'),
('Batman: O Cavaleiro das Trevas', 2008, 'Batman enfrenta o Coringa, um gênio do crime que quer mergulhar Gotham City na anarquia.'),
('Clube da Luta', 1999, 'Um trabalhador insone e um vendedor de sabonetes formam um clube de luta clandestino.'),
('Forrest Gump: O Contador de Histórias', 1994, 'A história de um homem com QI baixo que alcança grandes feitos na vida.'),
('Um Sonho de Liberdade', 1994, 'Dois homens presos criam um vínculo ao longo dos anos, encontrando consolo e eventual redenção.'),
('O Senhor dos Anéis: A Sociedade do Anel', 2001, 'Um jovem hobbit parte em uma jornada para destruir um anel poderoso.'),
('Star Wars: Episódio IV - Uma Nova Esperança', 1977, 'Um jovem fazendeiro se junta a uma rebelião para salvar a galáxia de um império maligno.'),
('Jurassic Park: O Parque dos Dinossauros', 1993, 'Um parque temático sofre uma grande falha de energia que permite que seus dinossauros clonados escapem.'),
('O Rei Leão', 1994, 'Um jovem príncipe leão foge de seu reino apenas para aprender o verdadeiro significado de responsabilidade e coragem.'),
('Gladiador', 2000, 'Um ex-general romano busca vingança contra o imperador corrupto que assassinou sua família.'),
('Titanic', 1997, 'Um jovem casal de classes sociais diferentes se apaixona a bordo do malfadado R.M.S. Titanic.'),
('Avatar', 2009, 'Um fuzileiro naval paraplégico enviado à lua Pandora em uma missão única se vê dividido entre seguir suas ordens e proteger o mundo que sente ser seu lar.'),
('Os Vingadores', 2012, 'Os heróis mais poderosos da Terra devem se unir para impedir um semideus de escravizar a humanidade.'),
('Harry Potter e a Pedra Filosofal', 2001, 'Um jovem descobre que é um bruxo e frequenta uma escola de magia.'),
('O Silêncio dos Inocentes', 1991, 'Uma jovem cadete do FBI deve confiar em um assassino manipulado e encarcerado para capturar outro serial killer.'),
('A Lista de Schindler', 1993, 'Na Polônia ocupada pelos nazistas durante a Segunda Guerra Mundial, Oskar Schindler gradualmente se preocupa com sua força de trabalho judaica após testemunhar sua perseguição pelos nazistas.');
